all: minisat-2.2.0.tar.gz sugar-v2-2-1.zip

minisat-2.2.0.tar.gz:
	wget http://minisat.se/downloads/minisat-2.2.0.tar.gz

sugar-v2-2-1.zip:
	wget https://cspsat.gitlab.io/sugar/package/sugar-v2-2-1.zip
